### PR TITLE
Update briandowns/spinner

### PR DESCRIPTION
**Pull request by mmotejlek**
Fix briandowns/spinner#110.

### CODE REVIEW

**Comment by ihcsim** [comment]
@mmotejlek Mind rebasing this branch to pick up the CI linter fix (#107)? Thanks.

**Comment by mmotejlek** [comment]
> @mmotejlek Mind rebasing this branch to pick up the CI linter fix (#107)? Thanks.

Done!

**Review by ihcsim — APPROVED** [review]
LGTM :+1:.

**Comment by mmotejlek** [comment]
@ihcsim I'm not authorized to merge in case I was supposed to merge it.

**Comment by ihcsim** [comment]
@bathina2 can you merge this?

**Review by bathina2 — APPROVED** [review]

**Pull request merged**
